name: validation_form
description: "Reactive Forms heavily inspire this model-driven approach to handling form inputs and validations."
version: 0.0.7
homepage: https://github.com/michaelnabil230/flutter_validation_form

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  phone_numbers_parser: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
