name: validation_form
description: "Reactive Forms heavily inspire this model-driven approach to handling form inputs and validations."
version: 0.0.5
homepage: https://github.com/michaelnabil230/flutter_validation_form

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  email_validator: ^3.0.0
  equatable: ^2.0.5
  phone_numbers_parser: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
